### ISSUE TITLE
BlockChain中getAllSpentTXOs方法

### ISSUE THREAD

**Issue by agentgb** [wangweiX/blockchain-java#1]
王维，你好：
BlockChain中getAllSpentTXOs方法，根据能解锁的交易输入得到已经花费的UTXO，这样做是不是有点问题。因为创造的交易输出有可能是找回给自己的零钱不属于花费的UTXO，不是这样吗

**Comment by wangweiX** [comment]
agentdb，你好。
判断一个交易输出（Transaction Output）是否被花费，这其中也包括找零的交易输出，主要看，这些交易输入如果在下次交易中，被交易输入（Transaction Input）所引用，那么这些交易输出就被花费了，反之，则未被花费。

这样解答，不知是否解决你的问题

**Comment by agentgb** [comment]
明白了明白了，之前想错了。判断是否是被花费，只要再交易输入中被引用得交易输出就是已被花费得交易输出，谢谢大佬
